language: python
dist: xenial
sudo: true
python:
  - 3.6
  - 3.7
install:
  - pip install -q -r requirements-dev.txt
script:
  - flake8
  - pytest libpythonpro

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1